config/routes.rb
Rails.application.routes.draw do
  root to: 'members#index'

  resources :members do
    member do
      get :profile
    end
  end

  get 'website/:key', to: 'members#redirect_to_website', as: :member_website
  get 'search', to: 'members#search', as: :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :member_id, presence: true
  validates :friend_id, presence: true, uniqueness: { scope: :member_id }
  validate :not_self

  belongs_to :member, counter_cache: true
  belongs_to :friend, class_name: 'Member', counter_cache: true

  private

  def not_self
    errors.add(:friend_id, "can't be equal to member") if member == friend
  end
end

app/models/member.rb
class Member < ApplicationRecord
  UNIQUE_ID_LENGTH = 6.freeze
  BASE_SHORT_URL = 'http://tiny.ut'.freeze
  WEBSITE_HTML_ELEMENTS = 'h1, h2, h3'.freeze

  validates :name, presence: true
  validates :url_key, presence: true
  validates :website_url, presence: true
  validates_format_of :website_url, with: URI::regexp(%w(http https))

  before_validation :generate_url_key, on: :create

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, :class_name => "Friendship", foreign_key: :friend_id
  has_many :inverse_friends, :through => :inverse_friendships, :source => :member

  scope :filter_by_heading, ->(keyword, member_id=nil) {
    if member_id
      Member.find_by_sql("select * from members, jsonb_array_elements_text(website_contents->'headings') as data
        where data ILIKE '%#{keyword}%' AND id != #{member_id} ORDER BY created_at DESC")
    else
      Member.find_by_sql("select * from members, jsonb_array_elements_text(website_contents->'headings') as data
        where data ILIKE '%#{keyword}%' ORDER BY created_at DESC")
    end
  }

  class << self
    def search(keyword, member_id=nil)
      filter_by_heading(keyword, member_id)
    end
  end

  private

  def generate_url_key
    unique_id = ([*('a'..'z'), *('A'..'Z'), *('0'..'9')]).sample(UNIQUE_ID_LENGTH).join

    if Member.where(url_key: unique_id).exists?
      generate_url_key
    end

    self.url_key = unique_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = if params[:search].present?
      Member.search(params[:search])
    else
      Member.order('created_at DESC')
    end.paginate(page: params[:page])
  end

  def new
    @member = Member.new
  end

  def create
    result = CreateMember.new(member_params).call

    @member = result.object

    if result.success
      flash[:success] = result.message
      redirect_to members_path
    else
      flash[:error] = result.message
      render :new
    end
  end

  def profile
    @member = Member.find_by(id: params[:id])

    if @member.present?
      render :profile
    else
      flash[:error] = 'Member could not be found'
      redirect_to members_path
    end
  end

  def redirect_to_website
    @member = Member.find_by(url_key: params[:key])

    redirect_to @member.website_url, status: 301
  end

  def search
    @members = Member.search(params[:search], params[:member_id]).paginate(page: params[:page])
  end

  private

  def member_params
    params.require(:member).permit(:name, :website_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def website_short_url(key)
    "#{Member::BASE_SHORT_URL}/#{key}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utrack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_all_members.html.erb
<table>
  <thead>
    <th>Name</th>
    <th>Website</th>
    <th></th>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= link_to website_short_url(member.url_key), member_website_path(member.url_key), target: '_blank' %></td>
        <td><%= link_to 'View Profile', profile_member_path(member) %></td>
      </tr>
    <% end %>
    <%= will_paginate @members %>
  </tbody>
</table>

app/views/members/_form.html.erb
<%= form_for @member do |f| %>
  <div><%= f.label :name %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.label :website %></div>
  <div><%= f.text_field :website_url %></div>
  <div><%= f.submit 'Create' %></div>
<% end %>

app/views/members/_search_results.html.erb
<table>
  <thead>
    <th>Name</th>
    <th>Website</th>
    <th>Headings</th>
    <th></th>
  </thead>
  <tbody>
    <% @members.group_by { |m| m }.each do |member, member_data| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.website_url %></td>
        <td><%= member_data.map(&:value) %>
        <td><%= link_to 'View Profile', profile_member_path(member) %></td>
      </tr>
    <% end %>
    <%= will_paginate @members %>
  </tbody>
</table>

app/views/members/index.html.erb
<%= form_tag(members_path, :method => 'get') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: 'Search' %>
    <div>
      <%= button_tag 'Search' %>
    </div>
  </div>
<% end %>

<p><%= link_to 'Add new Member', new_member_path %></p>

<% if params[:search].present? %>
  <%= render partial: 'search_results', members: @members %>
<% else %>
  <%= render partial: 'all_members', members: @members %>
<% end %>

app/views/members/new.html.erb
<%= render partial: 'form' %>

app/views/members/profile.html.erb
<%= form_tag(search_path, :method => 'get') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: 'Search' %>
    <%= hidden_field_tag :member_id, @member.id %>
    <div>
      <%= button_tag 'Search' %>
    </div>
  </div>
<% end %>

<p><%= @member.name %></p>
<p><%= @member.website_url %></p>
<p><%= @member.friendships_count %></p>

app/views/members/search.html.erb
<%= render partial: 'search_results' %>